apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: hello-nginx
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-04-27T12:02:21Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: hello-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hello-world-chart
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: hello-world-chart-0.1.0
  name: hello-nginx-hello-world-chart
  namespace: default
  resourceVersion: "5517"
  uid: 1c8f3fbd-c2ee-4008-b5f6-f736b103445b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: hello-nginx
      app.kubernetes.io/name: hello-world-chart
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hello-nginx
        app.kubernetes.io/name: hello-world-chart
    spec:
      containers:
      - image: nginx:1.16.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: hello-world-chart
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: hello-nginx-hello-world-chart
      serviceAccountName: hello-nginx-hello-world-chart
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-04-27T12:02:26Z"
    lastUpdateTime: "2023-04-27T12:02:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-04-27T12:02:21Z"
    lastUpdateTime: "2023-04-27T12:02:26Z"
    message: ReplicaSet "hello-nginx-hello-world-chart-86b664f55c" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
