apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-world-chart.fullname" . }}-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to my custom nginx page</title>
    </head>
    <body>
      <h1>Hello, world!</h1>
      <p>This is my custom nginx page.</p>
    </body>
    </html>
